name: simulation
root: ./

pre_window: export UAV_NAME=uav1; export PROFILER=true
startup_window: control_test
windows:
  - roscore:
      layout: even-vertical
      panes:
        - roscore
  - gazebo:
      layout: even-vertical
      panes:
        - waitForRos; roslaunch simulation simulation.launch gui:=false
  - spawn:
      layout: even-vertical
      panes:
        - waitForSimulation; spawn 1 --run --delete --enable-rangefinder --enable-ground-truth --enable-bluefox-camera --file ~/mrs_workspace/src/uav_core/ros_packages/mrs_odometry/config/init_pose/init_pose.csv
  - control:
      layout: even-vertical
      panes:
        - waitForOdometry; roslaunch mrs_mav_manager simulation.launch
  - control_test:
      layout: even-vertical
      panes:
        - 'waitForControl; roslaunch mrs_testing control_test.launch'
  - rviz:
      layout: even-vertical
      panes:
        - waitForOdometry; roslaunch mrs_testing rviz_control_test.launch
        - waitForOdometry; sleep 3; ~/.i3/layout_manager.sh simulation2
  - optic_flow:
      layout: even-vertical
      panes:
        - waitForRos; roslaunch optic_flow simulation.launch
