name: simulation
root: ./

pre_window: export UAV_NAME=uav1; export PROFILER=false
startup_window: control_test
windows:
  - roscore:
      layout: even-vertical
      panes:
        - roscore
  - gazebo:
      layout: even-vertical
      panes:
        - waitForRos; roslaunch simulation simulation.launch gui:=true
  - spawn:
      layout: even-vertical
      panes:
        - waitForSimulation; spawn 1 --run --delete --enable-rangefinder --enable-ground-truth --enable-bluefox-camera
  - control:
      layout: even-vertical
      panes:
        - waitForOdometry; roslaunch mrs_uav_manager simulation_f550_gps.launch
  - control_test:
      layout: even-vertical
      panes:
        - 'waitForControl; roslaunch mrs_testing control_test.launch'
  - rviz:
      layout: even-vertical
      panes:
        - waitForOdometry; roslaunch mrs_testing rviz_control_test.launch
        - waitForOdometry; sleep 3; read; ~/.i3/layout_manager.sh simulation_test
  - optic_flow:
      layout: even-vertical
      panes:
        - waitForRos; roslaunch mrs_optic_flow simulation.launch
